apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: tcpproxy
spec:
  ports:
  - port: 8023
    protocol: TCP
    targetPort: 8023
  selector:
    app: tcpproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
