apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: tcpproxy
    name: tcpproxy
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tcpproxy
      deploymentconfig: tcpproxy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: tcpproxy
          deploymentconfig: tcpproxy
      spec:
        containers:
        - args:
          - -l
          - $(listenAddr)
          - -r
          - $(remoteAddr)
          - -logconn
          - $(logConnections)
          command:
          - tcpproxy
          env:
          - name: ClusterEnvironment
            value: production
          - name: listenAddr
            value: 0.0.0.0:8023
          - name: remoteAddr
            value: 10.0.0.208:3333
          - name: logConnections
            value: "true"
          image: quay.io/bigg01/tcpproxy
          imagePullPolicy: Always
          name: tcpproxy
          resources:
            limits:
              cpu: 150m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
